### ISSUE TITLE
test

### ISSUE THREAD

**Issue by matmair** [invenhost/org#1]
```[tasklist]
### Tasks
- [ ] https://github.com/invenhost/InvenTree/issues/68
- [ ] https://github.com/invenhost/InvenTree/issues/54
- [ ] https://github.com/invenhost/InvenTree/issues/2
- [ ] https://github.com/invenhost/InvenTree/issues/21
```
